### ISSUE TITLE
error executing neu

### ISSUE THREAD

**Issue by tridoxx** [neutralinojs/neutralinojs-cli#160]
hi, i installed neutralino on linux, pop_os based debian, and i have this error when i run the command, "neu", i have the last version of node and install using the doc, of the website here the link, thanks for comments. https://neutralino.js.org/docs/getting-started/your-first-neutralinojs-app.

```

/usr/local/lib/node_modules/@neutralinojs/neu/src/utils.js:42
    return path?.replace(/^\//, '');
                ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@neutralinojs/neu/src/modules/downloader.js:7:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@neutralinojs/neu/src/modules/creator.js:4:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)

```

**Comment by tridoxx** [comment]
Excuse me, apparently I had 2 versions of nodejs, and the system was taking 12, instead of 18, it works for me, thank you very much anyway

**Comment by pathange-s** [comment]
"Optional chaining", not supported in v<14.x
