### ISSUE TITLE
error instalation

### ISSUE THREAD

**Issue by xor256** [neutralinojs/neutralinojs-cli#188]
```
neu create myapp
/usr/local/lib/node_modules/@neutralinojs/neu/src/utils.js:42
    return path?.replace(/^\//, '');
                ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@neutralinojs/neu/src/modules/downloader.js:7:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@neutralinojs/neu/src/modules/creator.js:4:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)

```

**Comment by AntumDeluge** [comment]
@shalithasuranga Thanks for the link. I was using my package manager's version of Node, which is 12. Switching to the more recent Snap package works (I don't know how to use the Flatpak version).

**Comment by shalithasuranga** [comment]
Closing this since the issue was resolved with this discussion. Thanks :tada:
