### ISSUE TITLE
"EACCES: permission denied" received when building "Getting Started" app

### ISSUE THREAD

**Issue by richb-hanover** [neutralinojs/neutralinojs-cli#54]
* I am starting out with neutralino to see if I like it. I have a fresh install of neutralino 2.3.0 (`yarn global add @neutralinojs/neu`) on macOS 10.15.7

* `neu create firstneuapp` worked as described in the "Getting Started". So did `cd firstneuapp && neu run`

* I then entered `neu build --release` and got this error:

```
Error: EACCES: permission denied, copyfile 'bin/neutralino-mac' -> 'dist/firstneuapp/firstneuapp-mac'
```

**Expected Behavior**  
I had expected to build the binaries without error

**Actual Behavior**  
The full output from the build step is below. Linux & Win10 binaries seem to be present (although I have not tested them). No macOS binary.

**Steps to Reproduce the Problem**  
 1. See description above
 2. Note the permissions on the *neutralino-mac* file in the `./bin` directory

**Specifications**  
* NeutralinoJs Version: [Version number of NeutralinoJs framework] 2.3.0
* NeutralinoJs CLI version: [neu-cli version] 5.0.0
* Platform: [Platform specifications]  macOS 10.15.7

**Full error log**
```
?130 firstneuapp % neu build --release
Bundling app...
Generating res.neu...
Copying binaries...
Error: EACCES: permission denied, copyfile 'bin/neutralino-mac' -> 'dist/firstneuapp/firstneuapp-mac'
    at Object.copyFileSync (fs.js:1941:3)
    at copyFile (/Users/richb/.config/yarn/global/node_modules/fs-extra/lib/copy-sync/copy-sync.js:67:6)
    at onFile (/Users/richb/.config/yarn/global/node_modules/fs-extra/lib/copy-sync/copy-sync.js:53:25)
    at getStats (/Users/richb/.config/yarn/global/node_modules/fs-extra/lib/copy-sync/copy-sync.js:48:44)
    at startCopy (/Users/richb/.config/yarn/global/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
    at handleFilterAndCopy (/Users/richb/.config/yarn/global/node_modules/fs-extra/lib/copy-sync/copy-sync.js:33:10)
    at Object.copySync (/Users/richb/.config/yarn/global/node_modules/fs-extra/lib/copy-sync/copy-sync.js:26:10)
    at Object.module.exports.bundleApp (/Users/richb/.config/yarn/global/node_modules/@neutralinojs/neu/src/modules/bundler.js:34:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Command.<anonymous> (/Users/richb/.config/yarn/global/node_modules/@neutralinojs/neu/src/commands/build.js:11:13) {
  errno: -13,
  syscall: 'copyfile',
  code: 'EACCES',
  path: 'bin/neutralino-mac',
  dest: 'dist/firstneuapp/firstneuapp-mac'
}
  _   _            _             _ _             _
 | \ | | ___ _   _| |_ _ __ __ _| (_)_ __   ___ (_)___
 |  \| |/ _ \ | | | __| '__/ _` | | | '_ \ / _ \| / __|
 | |\  |  __/ |_| | |_| | | (_| | | | | | | (_) | \__ \
 |_| \_|\___|\__,_|\__|_|  \__,_|_|_|_| |_|\___// |___/
                                              |__/
Please check the ./dist directory!

√ firstneuapp % ll
total 32
drwxr-xr-x   11 richb  staff   352B Jun 19 07:33 .
drwxr-xr-x  307 richb  staff   9.6K Jun 19 07:28 ..
-rw-r--r--    1 richb  staff   137B Jun 19 07:28 .gitignore
-rw-r--r--    1 richb  staff   1.1K Jun 19 07:28 LICENSE
-rw-r--r--    1 richb  staff   379B Jun 19 07:28 README.md
drwxr-xr-x    6 richb  staff   192B Jun 19 07:28 bin
drwxr-xr-x    3 richb  staff    96B Jun 19 07:33 dist
-rw-r--r--    1 richb  staff   785B Jun 19 07:28 neutralino.config.json
-rw-r--r--    1 richb  staff     0B Jun 19 07:29 neutralinojs.log
drwxr-xr-x    6 richb  staff   192B Jun 19 07:28 resources
drwxr-xr-x    4 richb  staff   128B Jun 19 07:33 temp

√ firstneuapp % ll dist
total 0
drwxr-xr-x   3 richb  staff    96B Jun 19 07:33 .
drwxr-xr-x  11 richb  staff   352B Jun 19 07:33 ..
drwxr-xr-x   5 richb  staff   160B Jun 19 07:33 firstneuapp

√ firstneuapp % ll dist/firstneuapp
total 9736
drwxr-xr-x  5 richb  staff   160B Jun 19 07:33 .
drwxr-xr-x  3 richb  staff    96B Jun 19 07:33 ..
-rw-r--r--  1 richb  staff   3.2M Jun 19 07:33 firstneuapp-linux
-rw-r--r--  1 richb  staff   1.5M Jun 19 07:33 firstneuapp-win.exe
-rw-r--r--  1 richb  staff    28K Jun 19 07:33 res.neu

?130 firstneuapp % ll bin
total 12456
drwxr-xr-x   6 richb  staff   192B Jun 19 07:28 .
drwxr-xr-x  11 richb  staff   352B Jun 19 07:33 ..
-rw-r--r--   1 richb  staff   418K Jun 19 07:28 WebView2Loader.dll
-rw-r--r--   1 richb  staff   3.2M Jun 19 07:28 neutralino-linux
--wxrw--wt   1 richb  staff   968K Jun 19 07:28 neutralino-mac
-rw-r--r--   1 richb  staff   1.5M Jun 19 07:28 neutralino-win.exe

?1 firstneuapp % neu version
  _   _            _             _ _             _
 | \ | | ___ _   _| |_ _ __ __ _| (_)_ __   ___ (_)___
 |  \| |/ _ \ | | | __| '__/ _` | | | '_ \ / _ \| / __|
 | |\  |  __/ |_| | |_| | | (_| | | | | | | (_) | \__ \
 |_| \_|\___|\__,_|\__|_|  \__,_|_|_|_| |_|\___// |___/
                                              |__/
--- Global ---
Neutralinojs binaries: v2.3.0
neu CLI: v5.0.0

--- Project: firstneuapp (js.neutralino.sample) ---
Neutralinojs binaries: v2.3.0
√ firstneuapp %
```

**Comment by shalithasuranga** [comment]
Yeah, @richb-hanover I will check and apply a fix soon. moved the issue to the CLI space btw.

**Comment by futurepaycc** [comment]
runner.js line 3 should: 0755
ref:
https://stackoverflow.com/questions/8756639/how-do-i-use-chmod-with-node-js

**Comment by lmmfranco** [comment]
Same happened to me on ubuntu 18.
Additionally trying to run the project prompted this error:
```
./dist/myapp/myapp-linux: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ./dist/myapp/myapp-linux)
```

I solved the issue by running:
```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt update
sudo apt install libstdc++6
```

I guess this requirement should be listed on docs, or installed by setup.

**Comment by shalithasuranga** [comment]
Hey.. applied a fix for this issue. Please check the latest version.

**Comment by richb-hanover** [comment]
@shalithasuranga Thanks for the note. I can confirm the EACCES error is gone, but I still cannot run the app from the command line or run the built app on my Mac. See the newest info in #55  Thanks again.
