### ISSUE TITLE
Getting Started: Can't 'run' or 'build' starter app

### ISSUE THREAD

**Issue by richb-hanover** [neutralinojs/neutralinojs-cli#55]
Using neutralinojs 2.4.0 / 5.1.3 on macOS 10.15.7, I followed the [First Neutralino App](https://neutralino.js.org/docs/getting-started/your-first-neutralinojs-app) steps:

```
yarn global add @neutralinojs/neu
neu create firstneuapp
cd firstneuapp
neu run
neu build --release
```
@shalithasuranga I am sorry to report that I received several error messages with the 5.1.3 build:

1. `neu run` flashed up the GUI very briefly, and gave a message *Application was terminated.*
2. `neu build --release` gave *Error: EACCES: permission denied, copyfile 'bin/neutralino-mac' -> 'dist/firstneuapp/firstneuapp-mac'* (This looks similar to #54 .)
3. Applying `chmod 764 bin/neutralino-mac` as suggested in a comment permits the build step to work, but...
4. Running `./dist/firstneuapp/firstneuapp-mac` gives *zsh: segmentation fault  ./dist/firstneuapp/firstneuapp-mac*

Here is the full output

```
√ github % yarn global add @neutralinojs/neu
yarn global v1.22.10
warning package.json: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Installed "@neutralinojs/neu@5.1.3" with binaries:
      - neu
✨  Done in 3.02s.
√ github % neu version
  _   _            _             _ _             _
 | \ | | ___ _   _| |_ _ __ __ _| (_)_ __   ___ (_)___
 |  \| |/ _ \ | | | __| '__/ _` | | | '_ \ / _ \| / __|
 | |\  |  __/ |_| | |_| | | (_| | | | | | | (_) | \__ \
 |_| \_|\___|\__,_|\__|_|  \__,_|_|_|_| |_|\___// |___/
                                              |__/
--- Global ---
Neutralinojs binaries: v2.4.0
Neutralinojs client: v1.0.0
neu CLI: v5.1.3
INFO Run this command inside your project directory to get project specific Neutralinojs version.
√ github % neu create firstneuapp
Downloading minimal template to firstneuapp directory...
Extracting template zip file..
Downloading Neutralinojs binaries..
Extracting zip file..
Finalizing and cleaning temp. files.
Downloading the Neutralinojs client..
Finalizing and cleaning temp. files.

----
Enter 'cd firstneuapp && neu run' to run your application.
  _   _            _             _ _             _
 | \ | | ___ _   _| |_ _ __ __ _| (_)_ __   ___ (_)___
 |  \| |/ _ \ | | | __| '__/ _` | | | '_ \ / _ \| / __|
 | |\  |  __/ |_| | |_| | | (_| | | | | | | (_) | \__ \
 |_| \_|\___|\__,_|\__|_|  \__,_|_|_|_| |_|\___// |___/
                                              |__/
√ github % cd firstneuapp
√ firstneuapp % neu run
Application was terminated.
√ firstneuapp % neu build --release
Bundling app...
Generating res.neu...
Copying binaries...
Error: EACCES: permission denied, copyfile 'bin/neutralino-mac' -> 'dist/firstneuapp/firstneuapp-mac'
    at Object.copyFileSync (fs.js:1941:3)
    at copyFile (/Users/richb/.config/yarn/global/node_modules/fs-extra/lib/copy-sync/copy-sync.js:67:6)
    at onFile (/Users/richb/.config/yarn/global/node_modules/fs-extra/lib/copy-sync/copy-sync.js:53:25)
    at getStats (/Users/richb/.config/yarn/global/node_modules/fs-extra/lib/copy-sync/copy-sync.js:48:44)
    at startCopy (/Users/richb/.config/yarn/global/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
    at handleFilterAndCopy (/Users/richb/.config/yarn/global/node_modules/fs-extra/lib/copy-sync/copy-sync.js:33:10)
    at Object.copySync (/Users/richb/.config/yarn/global/node_modules/fs-extra/lib/copy-sync/copy-sync.js:26:10)
    at Object.module.exports.bundleApp (/Users/richb/.config/yarn/global/node_modules/@neutralinojs/neu/src/modules/bundler.js:34:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Command.<anonymous> (/Users/richb/.config/yarn/global/node_modules/@neutralinojs/neu/src/commands/build.js:11:13) {
  errno: -13,
  syscall: 'copyfile',
  code: 'EACCES',
  path: 'bin/neutralino-mac',
  dest: 'dist/firstneuapp/firstneuapp-mac'
}
  _   _            _             _ _             _
 | \ | | ___ _   _| |_ _ __ __ _| (_)_ __   ___ (_)___
 |  \| |/ _ \ | | | __| '__/ _` | | | '_ \ / _ \| / __|
 | |\  |  __/ |_| | |_| | | (_| | | | | | | (_) | \__ \
 |_| \_|\___|\__,_|\__|_|  \__,_|_|_|_| |_|\___// |___/
                                              |__/
Please check the ./dist directory!
√ firstneuapp % ll
total 32
drwxr-xr-x   11 richb  staff   352B Jul  4 07:34 .
drwxr-xr-x  308 richb  staff   9.6K Jul  4 07:34 ..
-rw-r--r--    1 richb  staff   185B Jul  4 07:34 .gitignore
-rw-r--r--    1 richb  staff   1.1K Jul  4 07:34 LICENSE
-rw-r--r--    1 richb  staff   515B Jul  4 07:34 README.md
drwxr-xr-x    6 richb  staff   192B Jul  4 07:34 bin
drwxr-xr-x    3 richb  staff    96B Jul  4 07:34 dist
-rw-r--r--    1 richb  staff   815B Jul  4 07:34 neutralino.config.json
-rw-r--r--    1 richb  staff     0B Jul  4 07:34 neutralinojs.log
drwxr-xr-x    6 richb  staff   192B Jul  4 07:34 resources
drwxr-xr-x    4 richb  staff   128B Jul  4 07:34 temp
√ firstneuapp % ll dist
total 0
drwxr-xr-x   3 richb  staff    96B Jul  4 07:34 .
drwxr-xr-x  11 richb  staff   352B Jul  4 07:34 ..
drwxr-xr-x   5 richb  staff   160B Jul  4 07:34 firstneuapp
√ firstneuapp % ll dist/firstneuapp
total 4664
drwxr-xr-x  5 richb  staff   160B Jul  4 07:34 .
drwxr-xr-x  3 richb  staff    96B Jul  4 07:34 ..
-rw-r--r--  1 richb  staff   753K Jul  4 07:34 firstneuapp-linux
-rw-r--r--  1 richb  staff   1.5M Jul  4 07:34 firstneuapp-win.exe
-rw-r--r--  1 richb  staff    32K Jul  4 07:34 res.neu
√ firstneuapp % ll bin
total 7384
drwxr-xr-x   6 richb  staff   192B Jul  4 07:34 .
drwxr-xr-x  11 richb  staff   352B Jul  4 07:34 ..
-rw-r--r--   1 richb  staff   418K Jul  4 07:34 WebView2Loader.dll
-rw-r--r--   1 richb  staff   753K Jul  4 07:34 neutralino-linux
--wxrw--wt   1 richb  staff   970K Jul  4 07:34 neutralino-mac
-rw-r--r--   1 richb  staff   1.5M Jul  4 07:34 neutralino-win.exe
```

**Comment by richb-hanover** [comment]
**Update:** I tried the same steps listed above with neutralino-cli 5.1.5, and had the same error messages.

**Comment by gaurav-nelson** [comment]
Same issue on Mac. 
```
❯ neu create testapp
Downloading minimal template to testapp directory...
Extracting template zip file..
Downloading Neutralinojs binaries..
Extracting zip file..
Finalizing and cleaning temp. files.
Downloading the Neutralinojs client..
Finalizing and cleaning temp. files.

----
Enter 'cd testapp && neu run' to run your application.
  _   _            _             _ _             _
 | \ | | ___ _   _| |_ _ __ __ _| (_)_ __   ___ (_)___
 |  \| |/ _ \ | | | __| '__/ _` | | | '_ \ / _ \| / __|
 | |\  |  __/ |_| | |_| | | (_| | | | | | | (_) | \__ \
 |_| \_|\___|\__,_|\__|_|  \__,_|_|_|_| |_|\___// |___/
                                              |__/
❯ cd testapp
❯ neu run
Application was terminated.
```

and building using `neu build --release` command results in error too, same as #59

**Comment by shalithasuranga** [comment]
Hey.. applied a fix for this issue. Please check the latest version

**Comment by gaurav-nelson** [comment]
Thank you @shalithasuranga 

However, I still see the same error message. 
```
❯ neu create myapp
Downloading minimal template to myapp directory...
Extracting template zip file..
Downloading Neutralinojs binaries..
Extracting zip file..
Finalizing and cleaning temp. files.
Downloading the Neutralinojs client..
Finalizing and cleaning temp. files.

----
Enter 'cd myapp && neu run' to run your application.
  _   _            _             _ _             _
 | \ | | ___ _   _| |_ _ __ __ _| (_)_ __   ___ (_)___
 |  \| |/ _ \ | | | __| '__/ _` | | | '_ \ / _ \| / __|
 | |\  |  __/ |_| | |_| | | (_| | | | | | | (_) | \__ \
 |_| \_|\___|\__,_|\__|_|  \__,_|_|_|_| |_|\___// |___/
                                              |__/

❯ cd myapp
❯ neu run
Application was terminated.
```

**Comment by shalithasuranga** [comment]
Hey.. @gaurav-nelson mm but there is no EACCES error? maybe it's another error. So, let's find out. Could you run the Mac binary manually with the following command?

```bash
// Run from myapp
$ ./bin/neutralino-mac --path=.
``

**Comment by richb-hanover** [comment]
Some progress... The EACCES error is gone with Neutralino v2.5.0, neutralino-cli v5.2.0

I still can't run the starter app (it flashes up the GUI, then gives `Application was terminated.` message)

I can build the app without error message, but attempting to run the app (two ways - see output below) gives a segfault.

(Once again, I'm running macOS 10.15.7,  node 14.8.0. Here's the output from a fresh start... Thanks.

```
√ github % yarn global add @neutralinojs/neu
yarn global v1.22.10
warning package.json: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Installed "@neutralinojs/neu@5.2.0" with binaries:
      - neu
✨  Done in 4.65s.

?139 github % neu version
  _   _            _             _ _             _
 | \ | | ___ _   _| |_ _ __ __ _| (_)_ __   ___ (_)___
 |  \| |/ _ \ | | | __| '__/ _` | | | '_ \ / _ \| / __|
 | |\  |  __/ |_| | |_| | | (_| | | | | | | (_) | \__ \
 |_| \_|\___|\__,_|\__|_|  \__,_|_|_|_| |_|\___// |___/
                                              |__/
--- Global ---
Neutralinojs binaries: v2.5.0
Neutralinojs client: v1.1.0
neu CLI: v5.2.0

--- Project: firstneuapp (js.neutralino.sample) ---
Neutralinojs binaries: v2.5.0
Neutralinojs client: v1.1.0

√ github % neu create firstneuapp
Downloading minimal template to firstneuapp directory...
Extracting template zip file..
Downloading Neutralinojs binaries..
Extracting zip file..
Finalizing and cleaning temp. files.
Downloading the Neutralinojs client..
Finalizing and cleaning temp. files.

----
Enter 'cd firstneuapp && neu run' to run your application.
  _   _            _             _ _             _
 | \ | | ___ _   _| |_ _ __ __ _| (_)_ __   ___ (_)___
 |  \| |/ _ \ | | | __| '__/ _` | | | '_ \ / _ \| / __|
 | |\  |  __/ |_| | |_| | | (_| | | | | | | (_) | \__ \
 |_| \_|\___|\__,_|\__|_|  \__,_|_|_|_| |_|\___// |___/
                                              |__/
√ github % cd firstneuapp

√ firstneuapp % neu run
Application was terminated.

√ firstneuapp % neu build --release
Bundling app...
Generating res.neu...
Copying binaries...
  _   _            _             _ _             _
 | \ | | ___ _   _| |_ _ __ __ _| (_)_ __   ___ (_)___
 |  \| |/ _ \ | | | __| '__/ _` | | | '_ \ / _ \| / __|
 | |\  |  __/ |_| | |_| | | (_| | | | | | | (_) | \__ \
 |_| \_|\___|\__,_|\__|_|  \__,_|_|_|_| |_|\___// |___/
                                              |__/
Please check the ./dist directory!

?130 firstneuapp % ./dist/firstneuapp/firstneuapp-mac
zsh: segmentation fault  ./dist/firstneuapp/firstneuapp-mac

?139 firstneuapp % ./bin/neutralino-mac --path=.
2021-07-18 09:06:37,411 ERROR [default] Resource file tree generation error: ./res.neu is missing.
zsh: segmentation fault  ./bin/neutralino-mac --path=.

```

**Comment by gaurav-nelson** [comment]
@shalithasuranga Yes I don't see the EACCESS error anymore. Similar to @richb-hanover I see the following error whit the command you suggested:
```
❯ neu run
Application was terminated.
❯ ./bin/neutralino-mac --path=.
2021-07-19 17:25:12,241 ERROR [default] Resource file tree generation error: ./res.neu is missing.
[1]    9303 segmentation fault  ./bin/neutralino-mac --path=.
```

**Comment by richb-hanover** [comment]
@shalithasuranga - As noted above, this is NOT SOLVED. Perhaps the ticket should be re-opened...

**Comment by shalithasuranga** [comment]
Hey @richb-hanover  yes agree. This issue may be related to the macOS version.
